databases:
  - name: shoe-store-db
    databaseName: shoe_store_db
    user: shoe_store_user

services:
  - type: web
    name: shoe-store-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shoe-store-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: PYTHON_VERSION
        value: 3.12.0